server:
    interface: 172.21.0.1@5335
    access-control: 172.21.0.2/32 allow

    module-config: "python iterator"

    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

    # Forwarder privacy / identity
    qname-minimisation: no
    hide-identity: yes
    hide-version: yes

    # Cache
    prefetch: yes

    edns-buffer-size: 1232
    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-first: no

    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 149.112.112.112@853#dns.quad9.net

python:
    python-script: "/usr/local/lib/wormlogic-pvp-dns/dnsbl_module.py"
